---
name: PR Runner

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: Setup
      uses: actions/checkout@v2

    - name: Use node version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Get npm cache directory
      id: npm-cache-dir
      run: |
        echo "::set-output name=dir::$(npm config get cache)"

    - uses: actions/cache@v2
      id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

   # Re: https://github.com/actions/setup-node/pull/125
    - name: Register Problem Matcher for TSC
      run: echo "##[add-matcher].github/tsc.json"

    - name: Install dependencies
      run: npx lerna bootstrap --ci --ignore-scripts

    - name: Lint
      run: npm run ci:lint

    - name: Run build
      run: npm run ci:build

    - name: Run tests
      run: npm run ci:test
